include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: true
    avoid_print: true
    prefer_single_quotes: true
    directives_ordering: true
    sort_constructors_first: true
    require_trailing_commas: true
    unawaited_futures: true
    public_member_api_docs: false

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
  errors:
    invalid_use_of_visible_for_testing_member: error
    invalid_use_of_protected_member: error
    missing_return: error
    dead_code: warning
    unused_import: warning

