name: devhub_gpt
description: DevHub — Flutter app scaffold following Clean Architecture and feature-first structure.
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.0
  riverpod_annotation: ^2.3.0

  # Navigation
  go_router: ^13.2.0

  # Networking
  dio: ^5.4.0
  retrofit: ^4.1.0
  pretty_dio_logger: ^1.3.0
  flutter_markdown: ^0.6.18

  # Local Storage / DB
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.0
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0

  # Utilities / Modeling
  freezed_annotation: ^2.4.0
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  intl: ^0.20.2
  crypto: ^3.0.3
  path: ^1.9.0
  path_provider: ^2.1.4
  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0

dev_dependencies:
  drift_dev: ^2.19.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  go_router_builder: ^2.4.1

  # Code Generation
  build_runner: ^2.4.0
  freezed: ^2.4.0
  json_serializable: ^6.8.0
  riverpod_generator: ^2.3.0
  retrofit_generator: ^8.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
