name: Web CI

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Generate freezed/json_serializable code
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Run custom lint (Riverpod + static checks)
        run: dart run custom_lint

      - name: Flutter analyze
        run: flutter analyze

      - name: Flutter tests
        run: flutter test

  web-build:
    runs-on: ubuntu-latest
    needs: lint-test
    strategy:
      matrix:
        renderer: [html, canvaskit]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build web bundle (${matrix.renderer})
        run: flutter build web --release --pwa-strategy=offline-first --tree-shake-icons --web-renderer ${{ matrix.renderer }}
      - name: Upload web artifact (html renderer)
        if: matrix.renderer == 'html'
        uses: actions/upload-artifact@v4
        with:
          name: web-build-html
          path: build/web

  deploy:
    runs-on: ubuntu-latest
    needs: web-build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download web artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build-html
          path: build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
